language: node_js
node_js: stable

branches:
  only:
    - master

addons:
  apt:
    packages:
    - graphicsmagick

before_install:
  - rvm install ruby --latest
  - gem install jekyll
  - npm install -g bower
  - bower install

script: npm run-script deploy

env: 
  global:
    - GH_REF: github.com/renyard/website.git
    - secure: "kv4wbUemgkqeaxjEf5oqbl2Ap8DUuIg5qUZSgHoAunlendD4jEVt5ATBKmDqKSvFun7XqqRaFEoOTc+P+vQwSEYYuFzCMnEkKPMrbZXzH0wHQNeBosnbfQVDZhhcGPrQiW1q4H0knQdGzc2iVfNTsxtA15QHYdT3jkJWXtSkxOWn0RcEsPZYDroED1F3YLfQkVDD8YxKMrFInEXI/Trl9FC/Hwi8W2e0djscs/ajx7XPc9gdbsZwhjY1gZDOwNzxXTBxxuPg4bKts5pFvaTXWcGGCqgrpgiXrOk8QBSW7xayEbP1URlhxnA5P7YDfjtm8bfC31cmmL3uHgMKQuRjNz2e4wlumFH0kUw3o7sLD8URgFCLt4kV1IRzg7qpeZm22mG9expE/zcLR15Hf32oLsgF1CDCqWxfisYrHJvVvy/Jht/mIPREcu63/5BlgSNQ1u3EMrg/m+UeJRpNfXvc9NH9YVkGhr02obk2QELCslJY5s6iNdEO03zkyD533L+tAb6TuXmiW9rxZwV2uqqpGjvfU70Xb+tcaf1SptagFlBoRDlxjZ8ZPF+Nd+GORJLN96zVuvfc1qg8M49W+KzF4B963JMPamUv8a6at3Sf8Kppn281pVHzyemovf9bqhK5Msmu4AJu6RPvJVLMkQi7tyHeIE0A/w5irV6rUGKVokA="
