# Site settings
title: Ian Renyard
email: ian@renyard.net
permalink: /:year/:month/:title.html
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.renyard.co.uk" # the base hostname & protocol for your site

destination: dist

include: [CNAME]
exclude: [
  bower.json,
  bower_components,
  css,
  deploy.sh,
  gulpfile.js,
  images,
  node_modules,
  package.json
]
keep_files: [
  css,
  images,
	js,
  fonts
]

twitter_username: renyard
github_username:  renyard
linkedin_username: renyard

timezone: Europe/London

# Build settings
markdown: kramdown
